server:
  port: 8003
spring:
  application:
    name: service-vod
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
aliyun:
  oss:
    file:
      accessKeyId: LTAI5t6FFbG7xK44BMpnmrhW #访问身份验证中用到用户标识
      accessKeySecret: 703wxTIApe2Bjf88rukjxMJw0iH4cc #用户用于加密签名字符串和oss用来验证签名字符串的密钥
