server:
  port: 8008
spring:
  application:
    name: service-acl
  redis:
    host: 192.168.163.135
    database: 0
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:com/zhang/eduacl/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl