server:
  port: 1000
spring:
  application:
    name: canal-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
  profiles:
    active: dev